### ISSUE TITLE
Shop not accessible over the internet

### ISSUE THREAD

**Issue by gabb96** [vinicioslc/tinfoil-hat#10]
Hello,
i cannot get the shop to work behind a reverse proxy(Nginxproxymanager) and domain name.
if i browse from computer or phone the request get logged and it serves the shop page, from tinfoil nothing.

Sun, 27 Aug 2023 20:37:52 GMT express:router dispatching GET /
Sun, 27 Aug 2023 20:37:52 GMT express:router query  : /
Sun, 27 Aug 2023 20:37:52 GMT express:router expressInit  : /
Sun, 27 Aug 2023 20:37:52 GMT express:router authMiddleware  : /
Sun, 27 Aug 2023 20:37:52 GMT express:router <anonymous>  : /
2023-08-27T20:37:52.465Z tinfoil-hat:request IN-> '/'
Sun, 27 Aug 2023 20:37:52 GMT express:router serveStatic  : /
Sun, 27 Aug 2023 20:37:52 GMT send stat "/games/index.html"
2023-08-27T20:37:52.466Z tinfoil-hat:request OUT-< '/'
Sun, 27 Aug 2023 20:37:52 GMT express:router <anonymous>  : /
Sun, 27 Aug 2023 20:37:52 GMT serve-index stat "/games/"
Sun, 27 Aug 2023 20:37:52 GMT serve-index readdir "/games/"
2023-08-27T20:37:52.527Z tinfoil-hat:ftp RUNING FTP CHECK ON DEVICES: 0
2023-08-27T20:37:52.527Z tinfoil-hat SCHEDULED NEXT EXECUTION IN 5 seconds

the folder structure should be correct. Any idea why tinfoil refuses to work ?

**Comment by ganonleboucher** [comment]
it may be fixed soon: https://github.com/a1ex4/ownfoil/issues/26#issuecomment-3915103942

**Comment by vinicioslc** [comment]
@ganonleboucher thanks for notify
