### ISSUE TITLE
Feature Request: Publish versionned tag on Docker Hub

### ISSUE THREAD

**Issue by Djiit** [vinicioslc/tinfoil-hat#11]
Hey,

It would be nice to have versionned tags on Docker, in addition to the already existing "main" and "latest".

Using Github Actions on "tag" trigger for instance?

Thanks!

**Comment by txchen** [comment]
@Djiit I created a server similar to this and I have published docker image, FYI: https://github.com/txchen/tinfoilbun

I created this because I didn't notice tinfoilhat has arm64 image and I need arm one, I realized that this can be implemented with super simple logic so I did it.

**Comment by vinicioslc** [comment]
arm version available here

https://hub.docker.com/layers/vinicioslc/tinfoil-hat/1.1.6/images/sha256-2093c3ec4e5a9a48374b624361ed2eda430ff4f18933a98f83810d808ddb0183?context=explore
