### ISSUE TITLE
How to use outside folder form buffalonas ? 

### ISSUE THREAD

**Issue by ryannguyentran** [vinicioslc/tinfoil-hat#15]
Hello.
I want to use the folder containing nsp files taken from my buffalo nas on the local network.
What I have to do ?
The IP of the nas for example is 192.168.0.111/nspfiles
Thank you

**Comment by vinicioslc** [comment]
Hello,

To use the Tinfoil-Hat Server with your NAS, you would need to mount the NAS directory to the Docker container. Here’s how you can do it:

First, ensure that your NAS is properly set up and that the NSP files are accessible over the network.
In the docker-compose.yml file, you will need to change the volume mount for the games directory. Replace /switch/games/ with the path to your NAS directory.

After making these changes, you can start the Docker container with docker-compose up.
Please note that this assumes that your Docker host machine has the necessary permissions to access the NAS and its files.

I hope this helps! If you have any other questions, feel free to ask.

Best regards
