### ISSUE TITLE
Add Saves?

### ISSUE THREAD

**Issue by littleferris** [vinicioslc/tinfoil-hat#3]
Would be cool if saves could be connected to the shop as well so saves can be shared across devices

**Comment by vinicioslc** [comment]
oh, this is interesting, how this is achieved in other "tinfoil" solutions ? You could gave-me some example of how the communication works ? How this project could serve the files to become visible on Tinfoil APP ?  @littleferris

**Comment by mobihen** [comment]
You can look at this project..

https://github.com/a1ex4/ownfoil

Also, it would be very nice to have that save per device.. so every device will have it's own saves backup and also can share from others...
@vinicioslc

**Comment by vinicioslc** [comment]
@mobihen this will help a lot, thank you for sending the project, it will help to understand how to implement this feature in tinfoil-hat, from what I understand the application will have to connect to NS and download the save backup NS -> SERVER periodically, would that be it? Have you ever used this feature?

**Comment by mobihen** [comment]
I understood just as you did. Haven't tried it yet tough.. You can try it if you have switch with saves..

**Comment by vinicioslc** [comment]
@littleferris @mobihen i just launched a new docker image that support download and listing tinfoil backups from switch using ftpd integrated module, if interested just pull the new version

**Comment by mobihen** [comment]
wow ! that was fast :) 
great job! you're very talented! 
can it be the same as with the sop configuration? 
does it includes multi-device save? like save per user?.. (since you have multi-user support)


p.s,
can you please tell how to name the file so tinfoil will recognize as:
New Game
Update
DLC

?

**Comment by vinicioslc** [comment]
@mobihen For now it only supports copying the backup files from the switch to the `/<homebrews folder>/Saves/Tinfoil||JKSV` folder, in the future MAYBE i will implement this additional support to group per device folder like `/Saves/<DEVICE IP or MAC>/Tinfoil||JKSV`.

About file naming
You just need to group your games into folders, like for example:
Game folder `Some game [NSZ]` and inside that folder put your xci, nsp or nsz files named with their `[titleid]` like for example:
`Some homebrew [0100FA401961E000][v0] (6.41 GB).nsz`
and the update or dlc like
`Some Update [0100FA401961E800][v196608] (0.20 GB).nsz`
Remember to mount the computer folder correctly if you are using docker or to configure the .env with the correct path to the homebrews folder

**Comment by mobihen** [comment]
thanks! but from where you know the update ID? the file with the vXXXX in it..?

**Comment by vinicioslc** [comment]
@mobihen open https://tinfoil.io/ and search for the titles

When download homebrews from torrent origins like nswtl.info they came named correctly
