### ISSUE TITLE
Games not shown

### ISSUE THREAD

**Issue by mobihen** [vinicioslc/tinfoil-hat#5]
When I get into the web interface, I only see the .json and the other file. 
Also, when I get into the shop from switch, I see those 2 files, but all the games are at "New Game" section. 

the problem is that I want to install the update files but I can't see them..

**Comment by vinicioslc** [comment]
Yes you will only see only the shop files from homepage, as the tinfoil app has some limit for files count in main page as described in the README.md

To avoid TinfoilApp freezes, the file listing was disabled, but you can download files copying links from /shop.json

Send the config that are you using and photos from the switch listing to allow us help you more precisely.

**Comment by mobihen** [comment]
the JSON is empty, when I look at it from linux. 
If I go from the switch, I can seed it in hex, but not something that I can copy/paste and use. 

are you familiar with the file naming on TinFoil?
to show as:
New Game
Update 
DLC
?

**Comment by vinicioslc** [comment]
so.. this is detected automatically by tinfoil when the homebrews are put on correct folder and listed on shop.json correctly, this could be some mismatch config in your setup

**Comment by mobihen** [comment]
can you tell what's the correct folder structure? file naming? 

thanks.

**Comment by vinicioslc** [comment]
In my setup the roms folder are structured like this:

![image](https://github.com/vinicioslc/tinfoil-hat/assets/10997022/129e9eda-5f47-4701-892e-7287be617c01)

And generate a structure like that:
![image](https://github.com/vinicioslc/tinfoil-hat/assets/10997022/a46c78c4-58b3-445f-9ffa-a40445338dc1)

**Comment by mobihen** [comment]
how can you tell the id of the game and the id of the update file?.. 

if I do 
cat shop.json, it's empty..

**Comment by vinicioslc** [comment]
the "shop.* files" at this folder are only "representative" to be displayed in the html server index, the Tinfoil Switch App will check every file titleid and fetch the game info from online catalog downloaded at nswitch

to access the game listing you should access throught [http://HOST:PORT/shop.json](http://127.0.0.1:3001/shop.json) since the server will scan files and folder to create files index at realtime

**Comment by mobihen** [comment]
yes, but how can I install the update files if they are not shown?.. 
I can only install games. 
But the update files are not listed so the game won't load. 
So how can I see those update files? 

Also, how can I know the id of the game update?
