### ISSUE TITLE
No way to browse games

### ISSUE THREAD

**Issue by dvlasoff** [vinicioslc/tinfoil-hat#8]
I have the shop setup and working. Some games show in New Releases and Recommended in Tinfoil. Also, search seems to work correctly. However, I cannot find a way to simply browse the list of games in Tinfoil. Is this by design or am I missing a configuration?

**Comment by vinicioslc** [comment]
This is a problem with Tinfoil. This project and server only list the folders and files for the Tinfoil Switch app, and then the app knows how to list and organize them for the user.

did you have another question ?

**Comment by dvlasoff** [comment]
No, but thank you for the response. I'll dig a little deeper into how Tinfoil sorts, etc.
